/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CodeSnippet {
    id: bigint;
    title: string;
    codeContent: string;
    language: string;
    timestamp: Time;
}
export interface BehaviorRule {
    id: bigint;
    ruleText: string;
    timestamp: Time;
}
export type Time = bigint;
export interface ImprovementLog {
    id: bigint;
    entryType: string;
    description: string;
    timestamp: Time;
}
export interface Memory {
    id: bigint;
    content: string;
    timestamp: Time;
}
export interface PersonalitySettings {
    communicationStyle: string;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    role: string;
    timestamp: Time;
}
export interface Command {
    id: bigint;
    name: string;
    timestamp: Time;
    actionDescription: string;
}
export interface Website {
    id: bigint;
    htmlContent: string;
    templateName: string;
    timestamp: Time;
    cssContent: string;
    jsContent: string;
}
export interface UserProfile {
    name: string;
    preferences: string;
    personalitySettings: PersonalitySettings;
}
export interface ExcelFile {
    id: bigint;
    analysisResult?: string;
    uploadTimestamp: Time;
    filename: string;
    rawData: Uint8Array;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateModule(moduleName: string): Promise<void>;
    addImprovementLog(entryType: string, description: string): Promise<void>;
    addMemory(content: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCommand(name: string, actionDescription: string): Promise<void>;
    createUserProfile(name: string): Promise<void>;
    deactivateModule(moduleName: string): Promise<void>;
    deleteCommand(id: bigint): Promise<void>;
    deleteMemory(id: bigint): Promise<void>;
    deleteRule(id: bigint): Promise<void>;
    executeCommand(name: string): Promise<string>;
    getActiveModules(): Promise<Array<string>>;
    getAllCommands(): Promise<Array<Command>>;
    getAllMemories(): Promise<Array<Memory>>;
    getAllRules(): Promise<Array<BehaviorRule>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatMessages(page: bigint, pageSize: bigint): Promise<Array<ChatMessage>>;
    getCodeSnippets(): Promise<Array<CodeSnippet>>;
    getExcelFiles(): Promise<Array<ExcelFile>>;
    getImprovementLogs(page: bigint, pageSize: bigint): Promise<Array<ImprovementLog>>;
    getPersonalitySettings(): Promise<PersonalitySettings>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWebsites(): Promise<Array<Website>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveChatMessage(role: string, content: string): Promise<void>;
    saveCodeSnippet(language: string, title: string, codeContent: string): Promise<void>;
    saveExcelAnalysis(fileId: bigint, analysis: string): Promise<void>;
    saveExcelFile(filename: string, rawData: Uint8Array): Promise<void>;
    saveWebsite(templateName: string, htmlContent: string, cssContent: string, jsContent: string): Promise<void>;
    setBehaviorRule(ruleText: string): Promise<void>;
    setPersonalitySettings(style: string): Promise<void>;
    updatePreferences(preferences: string): Promise<void>;
}
import type { ExcelFile as _ExcelFile, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateModule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateModule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateModule(arg0);
            return result;
        }
    }
    async addImprovementLog(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addImprovementLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImprovementLog(arg0, arg1);
            return result;
        }
    }
    async addMemory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemory(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCommand(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCommand(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCommand(arg0, arg1);
            return result;
        }
    }
    async createUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0);
            return result;
        }
    }
    async deactivateModule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateModule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateModule(arg0);
            return result;
        }
    }
    async deleteCommand(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCommand(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCommand(arg0);
            return result;
        }
    }
    async deleteMemory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMemory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMemory(arg0);
            return result;
        }
    }
    async deleteRule(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRule(arg0);
            return result;
        }
    }
    async executeCommand(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.executeCommand(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.executeCommand(arg0);
            return result;
        }
    }
    async getActiveModules(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveModules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveModules();
            return result;
        }
    }
    async getAllCommands(): Promise<Array<Command>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCommands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCommands();
            return result;
        }
    }
    async getAllMemories(): Promise<Array<Memory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemories();
            return result;
        }
    }
    async getAllRules(): Promise<Array<BehaviorRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRules();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: bigint, arg1: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0, arg1);
            return result;
        }
    }
    async getCodeSnippets(): Promise<Array<CodeSnippet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCodeSnippets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCodeSnippets();
            return result;
        }
    }
    async getExcelFiles(): Promise<Array<ExcelFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExcelFiles();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExcelFiles();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImprovementLogs(arg0: bigint, arg1: bigint): Promise<Array<ImprovementLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImprovementLogs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImprovementLogs(arg0, arg1);
            return result;
        }
    }
    async getPersonalitySettings(): Promise<PersonalitySettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalitySettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalitySettings();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebsites(): Promise<Array<Website>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsites();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveChatMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveChatMessage(arg0, arg1);
            return result;
        }
    }
    async saveCodeSnippet(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCodeSnippet(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCodeSnippet(arg0, arg1, arg2);
            return result;
        }
    }
    async saveExcelAnalysis(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExcelAnalysis(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExcelAnalysis(arg0, arg1);
            return result;
        }
    }
    async saveExcelFile(arg0: string, arg1: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExcelFile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExcelFile(arg0, arg1);
            return result;
        }
    }
    async saveWebsite(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWebsite(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWebsite(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setBehaviorRule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBehaviorRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBehaviorRule(arg0);
            return result;
        }
    }
    async setPersonalitySettings(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPersonalitySettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPersonalitySettings(arg0);
            return result;
        }
    }
    async updatePreferences(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreferences(arg0);
            return result;
        }
    }
}
function from_candid_ExcelFile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExcelFile): ExcelFile {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    analysisResult: [] | [string];
    uploadTimestamp: _Time;
    filename: string;
    rawData: Uint8Array;
}): {
    id: bigint;
    analysisResult?: string;
    uploadTimestamp: Time;
    filename: string;
    rawData: Uint8Array;
} {
    return {
        id: value.id,
        analysisResult: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.analysisResult)),
        uploadTimestamp: value.uploadTimestamp,
        filename: value.filename,
        rawData: value.rawData
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExcelFile>): Array<ExcelFile> {
    return value.map((x)=>from_candid_ExcelFile_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
