/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Command = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'timestamp' : Time,
  'actionDescription' : IDL.Text,
});
export const Memory = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const BehaviorRule = IDL.Record({
  'id' : IDL.Nat,
  'ruleText' : IDL.Text,
  'timestamp' : Time,
  'priority' : IDL.Nat,
});
export const PersonalitySettings = IDL.Record({
  'communicationStyle' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'preferences' : IDL.Text,
  'personalitySettings' : PersonalitySettings,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Time,
});
export const CodeSnippet = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'codeContent' : IDL.Text,
  'language' : IDL.Text,
  'timestamp' : Time,
});
export const ExcelFile = IDL.Record({
  'id' : IDL.Nat,
  'analysisResult' : IDL.Opt(IDL.Text),
  'uploadTimestamp' : Time,
  'filename' : IDL.Text,
  'rawData' : IDL.Vec(IDL.Nat8),
});
export const ImprovementLog = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const Website = IDL.Record({
  'id' : IDL.Nat,
  'htmlContent' : IDL.Text,
  'templateName' : IDL.Text,
  'timestamp' : Time,
  'cssContent' : IDL.Text,
  'jsContent' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateModule' : IDL.Func([IDL.Text], [], []),
  'addImprovementLog' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addMemory' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCommand' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createUserProfile' : IDL.Func([IDL.Text], [], []),
  'deactivateModule' : IDL.Func([IDL.Text], [], []),
  'deleteCommand' : IDL.Func([IDL.Nat], [], []),
  'deleteMemory' : IDL.Func([IDL.Nat], [], []),
  'deleteRule' : IDL.Func([IDL.Nat], [], []),
  'executeCommand' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getActiveModules' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllCommands' : IDL.Func([], [IDL.Vec(Command)], ['query']),
  'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getAllRules' : IDL.Func([], [IDL.Vec(BehaviorRule)], ['query']),
  'getAllRulesOrdered' : IDL.Func([], [IDL.Vec(BehaviorRule)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getCodeSnippets' : IDL.Func([], [IDL.Vec(CodeSnippet)], ['query']),
  'getExcelFiles' : IDL.Func([], [IDL.Vec(ExcelFile)], ['query']),
  'getImprovementLogs' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ImprovementLog)],
      ['query'],
    ),
  'getPersonalitySettings' : IDL.Func([], [PersonalitySettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCodeSnippet' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveExcelAnalysis' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveExcelFile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'saveOnboardingComplete' : IDL.Func([IDL.Bool], [], []),
  'saveWebsite' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'setBehaviorRule' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setPersonalitySettings' : IDL.Func([IDL.Text], [], []),
  'updatePreferences' : IDL.Func([IDL.Text], [], []),
  'updateRulePriority' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Command = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'timestamp' : Time,
    'actionDescription' : IDL.Text,
  });
  const Memory = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const BehaviorRule = IDL.Record({
    'id' : IDL.Nat,
    'ruleText' : IDL.Text,
    'timestamp' : Time,
    'priority' : IDL.Nat,
  });
  const PersonalitySettings = IDL.Record({ 'communicationStyle' : IDL.Text });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'preferences' : IDL.Text,
    'personalitySettings' : PersonalitySettings,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Time,
  });
  const CodeSnippet = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'codeContent' : IDL.Text,
    'language' : IDL.Text,
    'timestamp' : Time,
  });
  const ExcelFile = IDL.Record({
    'id' : IDL.Nat,
    'analysisResult' : IDL.Opt(IDL.Text),
    'uploadTimestamp' : Time,
    'filename' : IDL.Text,
    'rawData' : IDL.Vec(IDL.Nat8),
  });
  const ImprovementLog = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const Website = IDL.Record({
    'id' : IDL.Nat,
    'htmlContent' : IDL.Text,
    'templateName' : IDL.Text,
    'timestamp' : Time,
    'cssContent' : IDL.Text,
    'jsContent' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateModule' : IDL.Func([IDL.Text], [], []),
    'addImprovementLog' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addMemory' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCommand' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createUserProfile' : IDL.Func([IDL.Text], [], []),
    'deactivateModule' : IDL.Func([IDL.Text], [], []),
    'deleteCommand' : IDL.Func([IDL.Nat], [], []),
    'deleteMemory' : IDL.Func([IDL.Nat], [], []),
    'deleteRule' : IDL.Func([IDL.Nat], [], []),
    'executeCommand' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getActiveModules' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllCommands' : IDL.Func([], [IDL.Vec(Command)], ['query']),
    'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getAllRules' : IDL.Func([], [IDL.Vec(BehaviorRule)], ['query']),
    'getAllRulesOrdered' : IDL.Func([], [IDL.Vec(BehaviorRule)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getCodeSnippets' : IDL.Func([], [IDL.Vec(CodeSnippet)], ['query']),
    'getExcelFiles' : IDL.Func([], [IDL.Vec(ExcelFile)], ['query']),
    'getImprovementLogs' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ImprovementLog)],
        ['query'],
      ),
    'getPersonalitySettings' : IDL.Func([], [PersonalitySettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCodeSnippet' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveExcelAnalysis' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveExcelFile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
    'saveOnboardingComplete' : IDL.Func([IDL.Bool], [], []),
    'saveWebsite' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'setBehaviorRule' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setPersonalitySettings' : IDL.Func([IDL.Text], [], []),
    'updatePreferences' : IDL.Func([IDL.Text], [], []),
    'updateRulePriority' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };