/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatThread {
  'id' : bigint,
  'moduleTag' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
}
export interface MemoryNode {
  'id' : bigint,
  'content' : string,
  'timestamp' : bigint,
}
export interface Plan {
  'id' : string,
  'status' : string,
  'goal' : string,
  'stepsJson' : string,
  'createdAt' : bigint,
}
export interface ThreadMessage {
  'id' : bigint,
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
  'threadId' : bigint,
}
export interface UserProfile {
  'name' : string,
  'onboardingComplete' : boolean,
  'preferences' : string,
  'personalitySettings' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMemory' : ActorMethod<[string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatThread' : ActorMethod<[string, [] | [string]], bigint>,
  'createUserProfile' : ActorMethod<[UserProfile], undefined>,
  'deleteChatThread' : ActorMethod<[bigint], boolean>,
  'deleteMemory' : ActorMethod<[bigint], boolean>,
  'deletePlan' : ActorMethod<[string], boolean>,
  'deleteThreadMessage' : ActorMethod<[bigint, bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatThreads' : ActorMethod<[], Array<ChatThread>>,
  'getMemories' : ActorMethod<[], Array<MemoryNode>>,
  'getPlanById' : ActorMethod<[string], [] | [Plan]>,
  'getPlans' : ActorMethod<[], Array<Plan>>,
  'getThreadMessages' : ActorMethod<
    [bigint, bigint, bigint],
    Array<ThreadMessage>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePlan' : ActorMethod<[string, string, string, string], boolean>,
  'saveThreadMessage' : ActorMethod<[bigint, string, string], bigint>,
  'updatePlan' : ActorMethod<[string, string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];