/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BehaviorRule {
  'id' : bigint,
  'ruleText' : string,
  'timestamp' : Time,
}
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'role' : string,
  'timestamp' : Time,
}
export interface CodeSnippet {
  'id' : bigint,
  'title' : string,
  'codeContent' : string,
  'language' : string,
  'timestamp' : Time,
}
export interface Command {
  'id' : bigint,
  'name' : string,
  'timestamp' : Time,
  'actionDescription' : string,
}
export interface ExcelFile {
  'id' : bigint,
  'analysisResult' : [] | [string],
  'uploadTimestamp' : Time,
  'filename' : string,
  'rawData' : Uint8Array,
}
export interface ImprovementLog {
  'id' : bigint,
  'entryType' : string,
  'description' : string,
  'timestamp' : Time,
}
export interface Memory {
  'id' : bigint,
  'content' : string,
  'timestamp' : Time,
}
export interface PersonalitySettings { 'communicationStyle' : string }
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'preferences' : string,
  'personalitySettings' : PersonalitySettings,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Website {
  'id' : bigint,
  'htmlContent' : string,
  'templateName' : string,
  'timestamp' : Time,
  'cssContent' : string,
  'jsContent' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateModule' : ActorMethod<[string], undefined>,
  'addImprovementLog' : ActorMethod<[string, string], undefined>,
  'addMemory' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCommand' : ActorMethod<[string, string], undefined>,
  'createUserProfile' : ActorMethod<[string], undefined>,
  'deactivateModule' : ActorMethod<[string], undefined>,
  'deleteCommand' : ActorMethod<[bigint], undefined>,
  'deleteMemory' : ActorMethod<[bigint], undefined>,
  'deleteRule' : ActorMethod<[bigint], undefined>,
  'executeCommand' : ActorMethod<[string], string>,
  'getActiveModules' : ActorMethod<[], Array<string>>,
  'getAllCommands' : ActorMethod<[], Array<Command>>,
  'getAllMemories' : ActorMethod<[], Array<Memory>>,
  'getAllRules' : ActorMethod<[], Array<BehaviorRule>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[bigint, bigint], Array<ChatMessage>>,
  'getCodeSnippets' : ActorMethod<[], Array<CodeSnippet>>,
  'getExcelFiles' : ActorMethod<[], Array<ExcelFile>>,
  'getImprovementLogs' : ActorMethod<[bigint, bigint], Array<ImprovementLog>>,
  'getPersonalitySettings' : ActorMethod<[], PersonalitySettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWebsites' : ActorMethod<[], Array<Website>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveChatMessage' : ActorMethod<[string, string], undefined>,
  'saveCodeSnippet' : ActorMethod<[string, string, string], undefined>,
  'saveExcelAnalysis' : ActorMethod<[bigint, string], undefined>,
  'saveExcelFile' : ActorMethod<[string, Uint8Array], undefined>,
  'saveWebsite' : ActorMethod<[string, string, string, string], undefined>,
  'setBehaviorRule' : ActorMethod<[string], undefined>,
  'setPersonalitySettings' : ActorMethod<[string], undefined>,
  'updatePreferences' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];