/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Plan {
    id: string;
    status: string;
    goal: string;
    stepsJson: string;
    createdAt: bigint;
}
export interface ChatThread {
    id: bigint;
    moduleTag?: string;
    name: string;
    createdAt: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MemoryNode {
    id: bigint;
    content: string;
    timestamp: bigint;
}
export interface UserProfile {
    name: string;
    onboardingComplete: boolean;
    preferences: string;
    personalitySettings: string;
}
export interface ThreadMessage {
    id: bigint;
    content: string;
    role: string;
    timestamp: bigint;
    threadId: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}

export interface Task {
    id: bigint;
    title: string;
    description: string;
    dueDate?: bigint;
    priority: string;
    completed: boolean;
    createdAt: bigint;
}
export interface Note {
    id: bigint;
    title: string;
    content: string;
    summary: string;
    tags: string[];
    createdAt: bigint;
    updatedAt: bigint;
}
export interface FinanceEntry {
    id: bigint;
    entryType?: string;
    amount: bigint;
    category: string;
    description: string;
    entryDate: bigint;
    createdAt: bigint;
}
export interface KnowledgeFolder {
    id: bigint;
    name: string;
    parentId: bigint | null;
    createdAt: bigint;
}
export interface WikiPage {
    id?: bigint;
    folderId: bigint;
    overviewSection: string;
    keyConceptsSection: string;
    tipsSection: string;
    lastEditedAt: bigint;
}
export interface Command {
    id: bigint;
    name: string;
    action: string;
    actionDescription: string;
    timestamp: bigint;
    createdAt: bigint;
}
export interface BehaviorRule {
    id: bigint;
    ruleText: string;
    priority: bigint;
    timestamp: bigint;
    createdAt: bigint;
}
export interface ModuleStatus {
    moduleId: string;
    active: boolean;
}
export interface LegacyChatMessage {
    id: bigint;
    role: string;
    content: string;
    timestamp: bigint;
}
export interface ImprovementLog {
    id: bigint;
    entryType: string;
    description: string;
    timestamp: bigint;
}
export interface ExcelFile {
    id: bigint;
    filename: string;
    data: Uint8Array;
    analysis: string;
    createdAt: bigint;
}
export interface Website {
    id: bigint;
    templateName: string;
    htmlContent: string;
    cssContent: string;
    jsContent: string;
    createdAt: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMemory(content: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChatThread(name: string, moduleTag: string | null): Promise<bigint>;
    createUserProfile(profile: UserProfile): Promise<void>;
    deleteChatThread(threadId: bigint): Promise<boolean>;
    deleteMemory(id: bigint): Promise<boolean>;
    deletePlan(id: string): Promise<boolean>;
    deleteThreadMessage(threadId: bigint, messageId: bigint): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatThreads(): Promise<Array<ChatThread>>;
    getMemories(): Promise<Array<MemoryNode>>;
    getPlanById(id: string): Promise<Plan | null>;
    getPlans(): Promise<Array<Plan>>;
    getThreadMessages(threadId: bigint, offset: bigint, limit: bigint): Promise<Array<ThreadMessage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePlan(id: string, goal: string, stepsJson: string, status: string): Promise<boolean>;
    saveThreadMessage(threadId: bigint, role: string, content: string): Promise<bigint>;
    updatePlan(id: string, goal: string, stepsJson: string, status: string): Promise<boolean>;
    getAllTasks(): Promise<Array<Task>>;
    addTask(title: string, description: string, deadline: bigint | null, priority: string): Promise<bigint>;
    updateTaskCompletion(id: bigint, completed: boolean): Promise<boolean>;
    deleteTask(id: bigint): Promise<boolean>;
    getAllNotes(): Promise<Array<Note>>;
    addNote(title: string, content: string, tags: string[]): Promise<bigint>;
    updateNote(id: bigint, title: string, content: string, tags: string[]): Promise<boolean>;
    deleteNote(id: bigint): Promise<boolean>;
    getAllFinanceEntries(): Promise<Array<FinanceEntry>>;
    addFinanceEntry(entryType: string, amount: bigint, category: string, description: string, entryDate: bigint): Promise<bigint>;
    deleteFinanceEntry(id: bigint): Promise<boolean>;
    getFolders(): Promise<Array<KnowledgeFolder>>;
    createFolder(name: string, parentId: bigint | null): Promise<bigint>;
    deleteFolder(id: bigint): Promise<boolean>;
    getWikiPageByFolder(folderId: bigint): Promise<WikiPage | null>;
    saveWikiPage(folderId: bigint, content: string): Promise<boolean>;
    getAllCommands(): Promise<Array<Command>>;
    createCommand(trigger: string, action: string, description: string): Promise<void>;
    deleteCommand(id: bigint): Promise<void>;
    getAllRules(): Promise<Array<BehaviorRule>>;
    getAllRulesOrdered(): Promise<Array<BehaviorRule>>;
    setBehaviorRule(ruleText: string, priority: bigint, enabled: boolean): Promise<void>;
    updateRulePriority(id: bigint, newPriority: bigint): Promise<void>;
    deleteRule(id: bigint): Promise<void>;
    getActiveModules(): Promise<Array<ModuleStatus>>;
    activateModule(moduleId: string): Promise<void>;
    deactivateModule(moduleId: string): Promise<void>;
    getChatMessages(offset: bigint, limit: bigint): Promise<Array<LegacyChatMessage>>;
    saveChatMessage(role: string, content: string): Promise<void>;
    getImprovementLogs(): Promise<Array<ImprovementLog>>;
    getExcelFiles(): Promise<Array<ExcelFile>>;
    saveExcelFile(filename: string, data: string): Promise<void>;
    saveExcelAnalysis(fileId: bigint, analysis: string): Promise<void>;
    getWebsites(): Promise<Array<Website>>;
    saveWebsite(url: string, title: string, contentJson: string): Promise<void>;
    saveOnboardingComplete(completed?: boolean): Promise<void>;
}
import type { ChatThread as _ChatThread, Plan as _Plan, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult, Task as _Task, Note as _Note, FinanceEntry as _FinanceEntry, KnowledgeFolder as _KnowledgeFolder, WikiPage as _WikiPage, Command as _Command, StoredBehaviorRule as _StoredBehaviorRule, ModuleStatus as _ModuleStatus, LegacyChatMessage as _LegacyChatMessage, ImprovementLogEntry as _ImprovementLogEntry, ExcelFile as _ExcelFile, Website as _Website } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMemory(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemory(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChatThread(arg0: string, arg1: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatThread(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatThread(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0);
            return result;
        }
    }
    async deleteChatThread(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatThread(arg0);
            return result;
        }
    }
    async deleteMemory(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMemory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMemory(arg0);
            return result;
        }
    }
    async deletePlan(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlan(arg0);
            return result;
        }
    }
    async deleteThreadMessage(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteThreadMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteThreadMessage(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatThreads(): Promise<Array<ChatThread>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatThreads();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatThreads();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemories(): Promise<Array<MemoryNode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemories();
            return result;
        }
    }
    async getPlanById(arg0: string): Promise<Plan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanById(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanById(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlans(): Promise<Array<Plan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlans();
            return result;
        }
    }
    async getThreadMessages(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<ThreadMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getThreadMessages(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThreadMessages(arg0, arg1, arg2);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePlan(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlan(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlan(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveThreadMessage(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveThreadMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveThreadMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePlan(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlan(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlan(arg0, arg1, arg2, arg3);
            return result;
        }
    }

    async getAllTasks(): Promise<Array<Task>> {
        const result = await this.actor.getAllTasks();
        return result.map(t => ({ ...t, dueDate: t.dueDate.length > 0 ? t.dueDate[0] : undefined }));
    }
    async addTask(title: string, description: string, deadline: bigint | null, priority: string): Promise<bigint> {
        return this.actor.addTask(title, description, deadline !== null ? [deadline] : [], priority);
    }
    async updateTaskCompletion(id: bigint, completed: boolean): Promise<boolean> {
        return this.actor.updateTaskCompletion(id, completed);
    }
    async deleteTask(id: bigint): Promise<boolean> {
        return this.actor.deleteTask(id);
    }
    async getAllNotes(): Promise<Array<Note>> {
        const result = await this.actor.getAllNotes();
        return result.map(n => ({
            ...n, summary: '',
            tags: n.tags ? n.tags.split(',').map((t: string) => t.trim()).filter(Boolean) : []
        }));
    }
    async addNote(title: string, content: string, tags: string[]): Promise<bigint> {
        return this.actor.addNote(title, content, tags.join(','));
    }
    async updateNote(id: bigint, title: string, content: string, tags: string[]): Promise<boolean> {
        return this.actor.updateNote(id, title, content, tags.join(','));
    }
    async deleteNote(id: bigint): Promise<boolean> {
        return this.actor.deleteNote(id);
    }
    async getAllFinanceEntries(): Promise<Array<FinanceEntry>> {
        const result = await this.actor.getAllFinanceEntries();
        return result.map(e => ({ ...e, entryDate: e.date }));
    }
    async addFinanceEntry(entryType: string, amount: bigint, category: string, description: string, entryDate: bigint): Promise<bigint> {
        return this.actor.addFinanceEntry(entryType, amount, category, description, entryDate);
    }
    async deleteFinanceEntry(id: bigint): Promise<boolean> {
        return this.actor.deleteFinanceEntry(id);
    }
    async getFolders(): Promise<Array<KnowledgeFolder>> {
        const result = await this.actor.getFolders();
        return result.map(f => ({ ...f, parentId: f.parentId.length > 0 ? f.parentId[0] : null }));
    }
    async createFolder(name: string, parentId: bigint | null): Promise<bigint> {
        return this.actor.createFolder(name, parentId !== null ? [parentId] : []);
    }
    async deleteFolder(id: bigint): Promise<boolean> {
        return this.actor.deleteFolder(id);
    }
    async getWikiPageByFolder(folderId: bigint): Promise<WikiPage | null> {
        const result = await this.actor.getWikiPageByFolder(folderId);
        if (result.length === 0) return null;
        const page = result[0];
        let parsed: { overview?: string; keyConcepts?: string; tips?: string } = {};
        try { parsed = JSON.parse(page.content); } catch { parsed = {}; }
        return {
            folderId: page.folderId,
            overviewSection: parsed.overview || page.content,
            keyConceptsSection: parsed.keyConcepts || '',
            tipsSection: parsed.tips || '',
            lastEditedAt: page.updatedAt
        };
    }
    async saveWikiPage(folderId: bigint, content: string): Promise<boolean> {
        return this.actor.saveWikiPage(folderId, content);
    }
    async getAllCommands(): Promise<Array<Command>> {
        const result = await this.actor.getAllCommands();
        return result.map(c => ({ id: c.id, name: c.trigger, action: c.action, actionDescription: c.description, timestamp: c.createdAt, createdAt: c.createdAt }));
    }
    async createCommand(trigger: string, action: string, description: string): Promise<void> {
        await this.actor.createCommand(trigger, action, description);
    }
    async deleteCommand(id: bigint): Promise<void> {
        await this.actor.deleteCommand(id);
    }
    async getAllRules(): Promise<Array<BehaviorRule>> {
        const result = await this.actor.getAllRules();
        return result.map(r => ({ id: r.id, ruleText: r.rule, priority: r.priority, timestamp: r.createdAt, createdAt: r.createdAt }));
    }
    async getAllRulesOrdered(): Promise<Array<BehaviorRule>> {
        const result = await this.actor.getAllRulesOrdered();
        return result.map(r => ({ id: r.id, ruleText: r.rule, priority: r.priority, timestamp: r.createdAt, createdAt: r.createdAt }));
    }
    async setBehaviorRule(ruleText: string, priority: bigint, enabled: boolean): Promise<void> {
        await this.actor.setBehaviorRule(ruleText, priority, enabled);
    }
    async updateRulePriority(id: bigint, newPriority: bigint): Promise<void> {
        await this.actor.updateRulePriority(id, newPriority);
    }
    async deleteRule(id: bigint): Promise<void> {
        await this.actor.deleteRule(id);
    }
    async getActiveModules(): Promise<Array<ModuleStatus>> {
        return this.actor.getActiveModules();
    }
    async activateModule(moduleId: string): Promise<void> {
        await this.actor.activateModule(moduleId);
    }
    async deactivateModule(moduleId: string): Promise<void> {
        await this.actor.deactivateModule(moduleId);
    }
    async getChatMessages(offset: bigint, limit: bigint): Promise<Array<LegacyChatMessage>> {
        return this.actor.getChatMessages(offset, limit);
    }
    async saveChatMessage(role: string, content: string): Promise<void> {
        await this.actor.saveChatMessage(role, content);
    }
    async getImprovementLogs(): Promise<Array<ImprovementLog>> {
        const result = await this.actor.getImprovementLogs();
        return result.map(l => ({ id: l.id, entryType: l.category, description: l.message, timestamp: l.timestamp }));
    }
    async getExcelFiles(): Promise<Array<ExcelFile>> {
        const result = await this.actor.getExcelFiles();
        return result.map(f => ({ id: f.id, filename: f.name, data: new Uint8Array(), analysis: '', createdAt: f.createdAt }));
    }
    async saveExcelFile(filename: string, data: string): Promise<void> {
        await this.actor.saveExcelFile(filename, data);
    }
    async saveExcelAnalysis(fileId: bigint, analysis: string): Promise<void> {
        await this.actor.saveExcelAnalysis(fileId, analysis);
    }
    async getWebsites(): Promise<Array<Website>> {
        const result = await this.actor.getWebsites();
        return result.map(s => {
            let parsed: { html?: string; css?: string; js?: string } = {};
            try { parsed = JSON.parse(s.contentJson); } catch { parsed = {}; }
            return { id: s.id, templateName: s.title, htmlContent: parsed.html || '', cssContent: parsed.css || '', jsContent: parsed.js || '', createdAt: s.savedAt };
        });
    }
    async saveWebsite(url: string, title: string, contentJson: string): Promise<void> {
        await this.actor.saveWebsite(url, title, contentJson);
    }
    async saveOnboardingComplete(_completed?: boolean): Promise<void> {
        await this.actor.saveOnboardingComplete();
    }
}
function from_candid_ChatThread_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatThread): ChatThread {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Plan]): Plan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    moduleTag: [] | [string];
    name: string;
    createdAt: bigint;
}): {
    id: bigint;
    moduleTag?: string;
    name: string;
    createdAt: bigint;
} {
    return {
        id: value.id,
        moduleTag: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.moduleTag)),
        name: value.name,
        createdAt: value.createdAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatThread>): Array<ChatThread> {
    return value.map((x)=>from_candid_ChatThread_n15(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
